### ISSUE TITLE
beforeLabel and afterLabel do not work properly when ltr=false

### ISSUE THREAD

**Issue by JaneSmith** [lemon3/slick-image-compare#1]
Hello. I've been trying this out on a personal website I've been putting together, and have a few issues.

At first I struggled with the default image order that Slick Image Compare produces... The readme shows a usage example like this:

```
<div id="my-div">
  <img src="01_before.jpg" alt="before" />
  <img src="01_after.jpg" alt="after" />
</div>
```

In this example, I would expect that the before-image would be shown on the left side of the comparison, and the after-image would be shown on the right side. That is what makes sense to me intuitively, this is what would match the HTML order (i.e. when JS is disabled), and it is also how other before/after image comparison implementations seem to behave (e.g. [img-comparison-slider](https://img-comparison-slider.sneas.io), [jquery-images-compare](https://github.com/sylvaincombes/jquery-images-compare)).

To my surprise, Slick Image Compare seems to invert this, and instead places the after-image on the left, and the before-image on the right. This seems backwards to me.

Eventually I found the `ltr` option, and my problem was solved by setting it to `false`. (Although I would argue that this is backwards... "before-after" would be left-to-right, so I would expect `true` to produce this, but instead it's the other way around.)

**Unfortunately, I then realised that `ltr=false` introduces a bug when using `beforeLabel` and `afterLabel`.**

```
<div data-sic="{
  ltr: false,
  afterLabel: 'after',
  beforeLabel: 'before'
}">
  <img src="01_before.jpg" alt="before" />
  <img src="01_after.jpg" alt="after" />
</div>
```

If you run the above code and drag the slider around, you will see that the after-label disappears when the after-img is fully visible, and the before-label disappears when the before-img is fully visible. In other words, when looking at the before-img, you see "after" written over the image.

**I suspect that the code to fade out the labels doesn't check the `ltr` value.**

***

Aside from that, I have a few other issues. I'm not sure whether or not to open separate issues for them, as I don't want to spam you. I'll just mention them here briefly for now:

- `new SlickImageCompare(...)` doesn't seem to properly handle classes, e.g. `.beforeafter`. It finds the first item with a matching class and activates that one, but ignores any further matching classes. All the examples on the readme use IDs instead, e.g. `#my-div`, so it seems like it's been designed around using one-time use. There is the `data-sic` approach provided, which works to activate every time, but that approach makes it impossible to activate specific groups of items.
- The documentation doesn't mention how to handle the CSS. Following the documentation examples, I get an unstyled component with no arrows. Importing the stylesheet works, but I have to do it with a messy path into node_modules, e.g. `import "../../node_modules/slick-image-compare/dist/style.css"`. I would prefer to import through the package directly, e.g. `import "slick-image-compare/dist/style.css"`, but this doesn't work. I think it's because your `package.json` file doesn't list the stylesheet as an export.

Thanks for your time, and for making this.

**Comment by lemon3** [comment]
i have just pushed an update (git/npm)

**Comment by lemon3** [comment]
see here: https://lemon3.github.io/slick-image-compare/
(section 'Multiple slider')

**Comment by JaneSmith** [comment]
Thanks for the update! Sorry for the delay in responding. This is an improvement, and for my specific use case is now working great. So I'm happy. Thank you.

However, I think it's still bugged, just the other way around now. If you set `ltr: false`, then `beforeLabel` fades when `afterLabel` should actually be fading, and `afterLabel` fades when `beforeLabel` should actually be fading.

For some reason this bug doesn't seem to appear on your demo website, but it happens when I try it on my end.

To make it easier to understand, I put together an online example: https://codesandbox.io/p/sandbox/4l2p3m

You can see that the second example on the preview page fades the labels incorrectly.

**Comment by lemon3** [comment]
okay, i'll have a look!
thanks for the codesandbox demo!

**Comment by lemon3** [comment]
> To make it easier to understand, I put together an online example: https://codesandbox.io/p/sandbox/4l2p3m
> 
> You can see that the second example on the preview page fades the labels incorrectly.

ltr issue fixed!
